/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Classes.Placeholder;
import Classes.Projetos;
import Classes.Usuarios;
import Classes.limiteTexto;
import DAO.UsuariosDAO;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.CardLayout;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author 291021
 */
public class Principal extends javax.swing.JFrame {

    EditUsuario editUsuarioPane;
    Configuracoes configPane;
    Cadastro cadastroPane;
    Geral geralPane;
    EditProj editProjPane;
    String layoutAtual;
    Usuarios usuarioLogado;
    NovoProjeto novoProjPane;
    AbrirTarefas tarefasPane;
    NovaTarefa novaTarefaPane;
    TarefaAberta tarefaAbertaPane;
    EditTarefa editTarefaPane;
    
    int idProjetoAberto;
    
    
    /**
     * Creates new form Principal
     */
        
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        layoutAtual =  "loginWindow";
        cadastroPane = new Cadastro();
        getContentPane().add(cadastroPane, "cadastroWindow");
        configPane = new Configuracoes();
        getContentPane().add(configPane, "configWindow");
        geralPane = new Geral();
        getContentPane().add(geralPane, "geralWindow");
        editProjPane = new EditProj();
        getContentPane().add(editProjPane, "editProjWindow");
        novoProjPane = new NovoProjeto();
        getContentPane().add(novoProjPane, "novoProjWindow");
        editUsuarioPane = new EditUsuario();
        getContentPane().add(editUsuarioPane, "editUsuarioWindow");
        tarefasPane = new AbrirTarefas();
        getContentPane().add(tarefasPane, "tarefasWindow");
        novaTarefaPane = new NovaTarefa();
        getContentPane().add(novaTarefaPane, "novaTarefaWindow");
        tarefaAbertaPane = new TarefaAberta();
        getContentPane().add(tarefaAbertaPane, "tarefaAbertaWindow");
        editTarefaPane = new EditTarefa();
        getContentPane().add(editTarefaPane, "editTarefaWindow");
        
        
        emailUsuario.setDocument(new limiteTexto(50));
        senhaUsuario.setDocument(new limiteTexto(20));
        
        Placeholder.addPlaceholder(emailUsuario, "Digite seu e-mail");
        Placeholder.addPlaceholder(senhaUsuario, "Digite sua senha");
        
        jMenuAjuda.setVisible(false);
    }

    public String getLayoutAtual() {
        return layoutAtual;
    }

    public void setLayoutAtual(String layoutAtual) {
        this.layoutAtual = layoutAtual;
    }

    public Usuarios getUsuarioLogado() {
        return usuarioLogado;
    }
    
    public void setUsuarioLogado(Usuarios usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }
    
    public void limparErro(){
        jLabelErro.setText(null);
    }
    
    public void desativarMenus(){
        jMenuItemLogout.setEnabled(false);
        jMenuProjetos.setEnabled(false);
        jMenuConta.setEnabled(false);
        jMenuTarefas.setEnabled(false);
    }
    
    public void ativarMenus(){
        jMenuItemLogout.setEnabled(true);
        jMenuProjetos.setEnabled(true);
        jMenuConta.setEnabled(true);
        jMenuTarefas.setEnabled(true);
    }
    
    public void setIdProjetoAberto(int idProjetoAberto){
        this.idProjetoAberto = idProjetoAberto;
    }
    
    public int getIdProjetoAberto(){
        return idProjetoAberto;
    }

    public void setTarefasPane(AbrirTarefas tarefasPane){
        this.tarefasPane = tarefasPane;
    }
    
    public AbrirTarefas getTarefasPane() {
        return tarefasPane;
    }
    
    public void setEditTarefaPane(EditTarefa editTarefaPane){
        this.editTarefaPane = editTarefaPane;
    }

    public JMenuItem getjMenuItemNovaTarefa() {
        return jMenuItemNovaTarefa;
    }

    public void setjMenuItemNovaTarefa(JMenuItem jMenuItemNovaTarefa) {
        this.jMenuItemNovaTarefa = jMenuItemNovaTarefa;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        emailUsuario = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        senhaUsuario = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();
        jLabelErro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConfiguracoes = new javax.swing.JMenu();
        jMenuItemServidor = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuProjetos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuTarefas = new javax.swing.JMenu();
        jMenuItemNovaTarefa = new javax.swing.JMenuItem();
        jMenuConta = new javax.swing.JMenu();
        jMenuItemApagarUsuario = new javax.swing.JMenuItem();
        jMenuItemEditarUsuario = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(640, 360));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 0));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel3Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel3.setLayout(jPanel3Layout);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(emailUsuario, gridBagConstraints);

        jLabelLogin.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel3.add(jLabelLogin, gridBagConstraints);

        jLabelSenha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        jPanel3.add(jLabelSenha, gridBagConstraints);

        senhaUsuario.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(senhaUsuario, gridBagConstraints);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 20);
        jPanel3.add(jButtonEntrar, gridBagConstraints);

        jButtonCadastro.setText("Cadastro");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel3.add(jButtonCadastro, gridBagConstraints);

        jLabelErro.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelErro.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        jPanel3.add(jLabelErro, gridBagConstraints);

        getContentPane().add(jPanel3, "loginWindow");

        jMenuConfiguracoes.setText("Configurações");

        jMenuItemServidor.setText("Servidor");
        jMenuItemServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServidorActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemServidor);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.setEnabled(false);
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemLogout);
        jMenuConfiguracoes.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemSair);

        jMenuBar1.add(jMenuConfiguracoes);

        jMenuProjetos.setText("Projetos");
        jMenuProjetos.setEnabled(false);

        jMenuItem1.setText("Novo projeto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuProjetos.add(jMenuItem1);

        jMenuBar1.add(jMenuProjetos);

        jMenuTarefas.setText("Tarefas");
        jMenuTarefas.setEnabled(false);

        jMenuItemNovaTarefa.setText("Nova tarefa");
        jMenuItemNovaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaTarefaActionPerformed(evt);
            }
        });
        jMenuTarefas.add(jMenuItemNovaTarefa);

        jMenuBar1.add(jMenuTarefas);

        jMenuConta.setText("Conta");
        jMenuConta.setEnabled(false);

        jMenuItemApagarUsuario.setText("Apagar meu usuário");
        jMenuItemApagarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApagarUsuarioActionPerformed(evt);
            }
        });
        jMenuConta.add(jMenuItemApagarUsuario);

        jMenuItemEditarUsuario.setText("Editar meu usuário");
        jMenuItemEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarUsuarioActionPerformed(evt);
            }
        });
        jMenuConta.add(jMenuItemEditarUsuario);

        jMenuBar1.add(jMenuConta);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServidorActionPerformed
        configPane = new Configuracoes(this, layoutAtual);
        getContentPane().add(configPane, "configWindow");
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), "configWindow");
    }//GEN-LAST:event_jMenuItemServidorActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        cadastroPane = new Cadastro(this);
        getContentPane().add(cadastroPane, "cadastroWindow");
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), "cadastroWindow");
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        UsuariosDAO userDAO = new UsuariosDAO();
        usuarioLogado = userDAO.logar(emailUsuario.getText(), senhaUsuario.getText());
        if(usuarioLogado == null){
            jLabelErro.setText("Login ou senha inválidos, tente novamente");
        } else{
            geralPane = new Geral(this);
            getContentPane().add(geralPane, "geralWindow");
            layoutAtual = "geralWindow";
            CardLayout layout = (CardLayout) getContentPane().getLayout();
            ativarMenus();
            layout.show(getContentPane(), "geralWindow");
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        layoutAtual =  "loginWindow";
        Placeholder.addPlaceholder(emailUsuario, "Digite seu e-mail");
        Placeholder.addPlaceholder(senhaUsuario, "Digite sua senha");
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), layoutAtual);
        limparErro();
        desativarMenus();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        novoProjPane = new NovoProjeto(geralPane, layoutAtual);
        getContentPane().add(novoProjPane, "novoProjWindow");
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), "novoProjWindow");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemApagarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApagarUsuarioActionPerformed
        Object[] options = { "Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(null, "Deseja apagar seu usuário? Essa ação é irreversível", "Apagar usuário", 1, 2, null, options, options[0]);
        if(opcao == 0){
            UsuariosDAO userDAO = new UsuariosDAO();
            userDAO.excluir(usuarioLogado);
            layoutAtual =  "loginWindow";
            Placeholder.addPlaceholder(emailUsuario, "Digite seu e-mail");
            Placeholder.addPlaceholder(senhaUsuario, "Digite sua senha");
            CardLayout layout = (CardLayout) getContentPane().getLayout();
            layout.show(getContentPane(), layoutAtual);
            limparErro();
            desativarMenus();
        }
    }//GEN-LAST:event_jMenuItemApagarUsuarioActionPerformed

    private void jMenuItemEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarUsuarioActionPerformed
        editUsuarioPane = new EditUsuario(this);
        getContentPane().add(editUsuarioPane, "editUsuarioWindow");
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), "editUsuarioWindow");
    }//GEN-LAST:event_jMenuItemEditarUsuarioActionPerformed

    private void jMenuItemNovaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaTarefaActionPerformed
        novaTarefaPane = new NovaTarefa(this);
        getContentPane().add(novaTarefaPane, "novaTarefaWindow");
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), "novaTarefaWindow");
    }//GEN-LAST:event_jMenuItemNovaTarefaActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        String mensagem = "Funcionalidades do sistema";
        JOptionPane.showMessageDialog(null, mensagem, "Ajuda", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        FlatCyanLightIJTheme.setup();
        
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelErro;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenu jMenuConta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemApagarUsuario;
    private javax.swing.JMenuItem jMenuItemEditarUsuario;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemNovaTarefa;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemServidor;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuProjetos;
    private javax.swing.JMenu jMenuTarefas;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPasswordField senhaUsuario;
    // End of variables declaration//GEN-END:variables
}
